-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : mar. 17 mai 2022 à 10:04
-- Version du serveur : 10.4.22-MariaDB
-- Version de PHP : 8.1.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `flavie_enrico_db`
--

-- --------------------------------------------------------

--
-- Structure de la table `rfa_mondes`
--

CREATE TABLE `rfa_mondes` (
  `id` int(11) NOT NULL,
  `nom` varchar(256) NOT NULL,
  `description` text NOT NULL,
  `image` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Déchargement des données de la table `rfa_mondes`
--

INSERT INTO `rfa_mondes` (`id`, `nom`, `description`, `image`) VALUES
(1, 'In the First Place', 'You have traveled from a faraway place and joined forces with the mythical being Ring, Together, you must defend the innocent from the sinister trainer Dragaux and his dark influence! It\'s up to you, player!', 'https://static.wikia.nocookie.net/ringfitadventure/images/9/96/Screenshot_2020-08-18_at_10.48.01_AM.png'),
(2, 'The Land of Night', 'You joined forces with Ring and nearly defeated Dragaux before the villain fled. The more Dragaux trains his dark influence, the stronger he will become. You must stop him!\r\n\r\nThe monsters that Dragaux created have started to attack people! There\'s a town nearby that may be in danger. Keep the townspeople safe from Dragaux\'s reign of terror!\r\n\r\nTogether with Ring, you protected the townspeople from the invading monsters. Yet there are surely others in danger. Press onward, player!', 'https://static.wikia.nocookie.net/ringfitadventure/images/e/ed/RingFitWorld2.PNG'),
(3, 'A Shining Jewel from the Heavens', 'Dragaux reached a land with a high human population. Work with Ring to stop Dragaux from spreading his dark influence!\r\n\r\nYou found Hubby from the General Store, but monsters have stolen his smoothie ingredients. Claiming he can\'t go home without a gift for his wife, Hubby went off in a search for a souvenir.\r\n\r\nHoney and Hubby have a new problem: their blender is broken. They said a new blender can be found in the General Factory, but that area is full of monsters!\r\n\r\nYou and Ring retrieved a new blender. Now you can buy smoothies at the General Store! Smoothies are great for recovery, so try to always have some handy!\r\n\r\nThe shining jewel that Honey was looking for was actually a power stolen from Ring! With his Smoothiecraft power now restored, Ring can make smoothies for you anytime!', 'https://static.wikia.nocookie.net/ringfitadventure/images/2/27/Screenshot_2020-09-21_at_3.37.58_PM.png'),
(4, 'The Nation of Sporta', 'Dragaux fled towards the Kingdom of Sporta. Ring believes the Sportans will be safe from Dragaux\'s influence, but you know better.\r\n\r\nDragaux is on the far side of a wide river that you cannot cross, but don\'t worry. The Sportan Commander will train you to cross that river the Sportan way!\r\n\r\nDragaux is on the far side of a wide river. Since you and Ring have no way across, the Sportan Commander began to train you how to cross like a Sportan!\r\n\r\nAfter you earned the Sportan Commander\'s approval, monsters suddenly appeared in the Sporta Treasury, where it\'s rumored that a shining jewel resides. Defeat the monsters and investigate the shining jewel!\r\n\r\nYou helped Ring defeat the monsters and recover the shining jewel, which held Ring\'s stolen River Rowing ability! Now you can cross the widest of rivers!\r\n\r\nYou helped Ring to recover his River Rowing ability, allowing you both to cross the Sportan River safely. Next up, Dragaux!', 'https://static.wikia.nocookie.net/ringfitadventure/images/f/f2/World_4_map.png'),
(5, 'Dragaux Vs. the Four Masters', 'You chased Dragaux from the Kingdom of Sporta and brought hope back to the Sportan people. Still, Dragaux\'s talk of tightening up his defenses is worrisome.\r\n\r\nYou met Allegra, the leg master. When she learned you\'re searching for Dragaux, she went to consult with the other masters. Go catch up with Allegra to see what they think.\r\n\r\nAllegra approved of you, but now you must earn the respect of Armando, the arm master.\r\n\r\nYou met the arm master, Armando. He\'s as intense as he is muscular, and he seems very suspicious of you. Watch out, for his test will be very tricky.\r\n\r\nYou have secured the approvals of Allegra and Armando. Now you must face the challenge of Abdonis, the abs master!\r\n\r\nYou rescued a young man trapped by fallen rocks. Now that the road is clear, you can continue your journey to meet Abdonis, the abs master!\r\n\r\nThe young man you rescued was actually Abdonis, the abs master himself! Now that you\'ve passed Abdonis\'s test, only Guru Andma, the balance master, remains!\r\n\r\nAfter you defeated Guru Andma\'s pet Ball in battle, all the Four Masters agreed to help you defeat Dragaux. They\'re now awaiting you at the stadium ahead.', 'https://static.wikia.nocookie.net/ringfitadventure/images/9/9b/World_5_map_2.png'),
(6, 'The Shrouded Land', 'Dragaux has captured The Four Masters! You must free them before whatever evil scheme he has in mind comes to pass!\r\n\r\nThis land is completely under the control of Dragaux\'s dark influence. Even the Four Masters are in danger of succumbing to its power. Stopping Dragaux will have to wait - you must save the Four Masters first!\r\n\r\nYou reunited with Allegra, Armando and Abdonis and discovered they are completely under the control of Dragaux\'s dark influence.\r\n\r\nYou reunited with Guru Andma and discovered that, just like Allegra, Armando and Abdonis, she was completely under the control of Dragaux\'s dark influence.', 'https://static.wikia.nocookie.net/ringfitadventure/images/8/8c/World_6_map.png'),
(7, 'The Forest Runner', 'Dragaux flew away with the Four Masters in his thrall. Give chase, and release them from his dark influence!\r\n\r\nWhile searching for Allegra, you learned of a woman named Dashley, who may know where to find her. Travel to Trotter\'s Grove and find Dashley!\r\n\r\nDashley cannot maintain her youth unless she keeps running, but monsters are blocking her jogging path in the forest. Help out Dashley so you can ask about Allegra!\r\n\r\nDashley was once Allegra\'s master. Allegra believed she could stop Dashley from running and thereby become top runner herself. Can Allegra be saved from the dark influence?', 'https://static.wikia.nocookie.net/ringfitadventure/images/f/f3/World_7_map.png'),
(8, 'Tears of Solar Plexia', 'Dashley agreed to watch over her student, Allegra, and try to be a positive influence. You and Ring moved on to the next land, following after Dragaux.\r\n\r\nThis land is plagued by a never-ending rain formed by the tears of a goddess called Solar Plexia, who should be bringing nothing but sunny days to her people. Perhaps you could help?\r\n\r\nThe priestess gave you directions to Solar Plexia\'s shrine but also revealed that the raindrops you gathered had no purpose. You began to wonder about the identity of the young man who mentioned the raindrops...\r\n\r\nAbdonis blocked the road leading to Solar Plexia\'s shrine. You realise now that the young man who mentioned the raindrops was also him in disguise. It struck you that Abdonis seems to know his way around this place awfully well...', 'https://static.wikia.nocookie.net/ringfitadventure/images/a/a0/Screenshot_20200818-071429.png'),
(9, 'Flex Dojo', 'The priestess serving Solar Plexia was really Abdonis\'s mother. But there\'s no time to digest that one, since Dragaux has stolen Solar Plexia\'s sphere of light!\r\n\r\nYou learned that Dragaux left Ring\'s orb of light with Armando in his Flex Dojo. Getting it back might be a problem. The orb(or sphere ) is ring\'s jump boost!!! You\'ve recovered Ring\'s Jump Boost ability! Dragaux responded by taking out his rage on Armando, sending monsters to his training gym. Aren\'t they on the same side?!', 'https://static.wikia.nocookie.net/ringfitadventure/images/e/ed/World_9_map.png'),
(10, 'Grandminion Gauntlet', 'You recovered Ring\'s Jump Boost ability! There\'s only one ability left until he\'s recovered all of his powers.\r\n\r\nThe children\'s paradise, Grandminion Gauntlet, stands between you and Dragaux. If you hope to make it to him, you\'ll need to win games against all of the Grandminions that Guru Andma trained.\r\n\r\nYou defeated Guru Andma and her Grandminions! Now to face off against Dragaux!', 'https://static.wikia.nocookie.net/ringfitadventure/images/3/3b/World_10_map.png'),
(11, 'Valley of Wishes', 'You were victorious in battle with Dragaux, but the villain remains undaunted. Insisting that the final victory (and indeed, the world) is his for the taking, he flew off to the next land.\r\n\r\nRing had an idea to save Dragaux by visiting the the Valley of Wishes, where any wishes can come true. However, the Valley proved elusive. A fortune-teller claimed that three friends hold the key to finding the Valley.\r\n\r\nTo reach the Valley, you must make three friends. Your first encounter was with Scarecruel, whose abrasive personality made you and Ring wonder if she could really be counted as a friend. when you meet Scarecruel she asks you to defeat some monsters without useing smoothies. she clams she dos not like them. After meeting Scarecruel, you encountered a young man whom Scarecruel ordered you to chase, but he was too fast for you.But the man dropped his crates. After breaking the crates you encouter a black matta slay After defeating it the Cowardly Strong man joins you. After meeting Scarecruel, your next encounter was the Cowardly Strongman, who seemed tough but was really a big softie. Now you have two friends...or do you?\r\n\r\nThree friends are needed to reach the Valley of Wishes. After the sadistic Scarecruel and the Cowardly Strongman, you met a third \"friend\", the vain Toned man. This dubious trio should satisfy the requirement to for entry into the Valley.\r\n\r\nYou were joined on your journey to the Valley of Wishes by the sadistic Scarecruel, the Cowardly Strongman and the vain Toned Man. The way to the Valley of Wishes has finally opened!', 'https://static.wikia.nocookie.net/ringfitadventure/images/1/12/World_11_map_2.png'),
(12, 'Wings of Daddalus', 'Scarecruel, Cowardly Strongman and Toned Man were revealed to be Allegra, Armando and Abdonis in disguise! However! Guru Andma\'s whereabouts is unknown, so be ready for anything!\r\n\r\nAt the Battle Gym, you won the birdy bolt that Daddalus needed to continue work on the airship. Now go deliver it to him at Upsurge Studio!\r\n\r\nYou defeated the monsters and recovered Ring\'s Wing Ability! Now you can cross the bluff and head toward Mt. Fearmenot.\r\n\r\nWith Ring\'s Wing Ability, you crossed the treacherous bluff at Mt. Fearmenot. Now celebrate the return of Ring\'s final power by beating Dragaux!', 'https://static.wikia.nocookie.net/ringfitadventure/images/d/db/Screenshot_20200827-103618.png'),
(13, 'El Dorago', 'You expected to fight Dragaux but encountered Guru Andma instead. It looks like Dragaux is using The Four Masters to buy time. But...time to do what?\r\n\r\nWhile you were occupied with the Four Masters. Dragaux built El Dorago, his utopia filled with the dark influence. With its citizens under Dragaux\'s spell, you\'re unlikely to get any help from them in your search.\r\n\r\nDragaux\'s dark influence has filled El Dorago. With the town\'s citizens all in his thrall, none of them are willing to help you in your search for Dragaux.', 'https://static.wikia.nocookie.net/ringfitadventure/images/f/fa/World_13_map.png'),
(14, 'Moppets Gone Missing', 'You found Dragaux\'s hiding place, but he escaped once again. What did he mean when he mentioned \"that power\"?\r\n\r\nYou met a ghost in a strange, fog-shrouded place. Ring denied being afraid of ghosts, but you could tell he totally is.\r\n\r\nYou and Ring arrived in town, where you learned that all the land\'s children have disappeared. You\'ll have to keep investigating to get to the bottom of this mystery.\r\n\r\nTogether with Ring, you defeated the monsters and freed the children. But the children were still stuck in ghost form! Is there any way to turn the children back to normal?!\r\n\r\nYou learned that the children became ghosts because they called Abdonis an old man during an abdominal exercise seminar.', 'https://static.wikia.nocookie.net/ringfitadventure/images/6/6a/World_14_map_1.png'),
(15, 'Quizton', 'Abdonis, upset the children were calling him \"old man\", turned them into ghosts. He repented when he saw their innocence again, but that doesn\'t get you any closer to finding Dragaux.\r\n\r\nEverything begins with a quiz and ends on a quiz in Quizton. You must figure out the correct answer to move onward!\r\n\r\nEverything begins with a quiz and ends on a quiz in Quizton. The chief\'s quiz is \"Which contains more vitamin C per gram?\".\r\n\r\nPlayer chose the right answer, so onward we go!\r\n\r\nAfter clearing the Battle Gym, the village chief\'s son approached you, wishing to discuss something.\r\n\r\nEverything begins with a quiz and ends on a quiz in Quizton. The chief\'s son\'s quiz is \"What does it mean to cool down?\"\r\n\r\nFortunately, Player knew the answer! What will you be quizzed on next?\r\n\r\nEverything begins with a quiz and ends on a quiz in Quizton. The chief\'s son\'s second quiz is \"Which exercise isn\'t among the Big Three?\" Answer the question correctly to move onward.', 'https://static.wikia.nocookie.net/ringfitadventure/images/b/ba/World_15_map_2.png'),
(16, 'The Steeliest Buns', 'Dragaux used his dark influence to toughen his abs. Now, he\'s going to strengthen the rest of his body too! Hurry after Dragaux, and stop him from getting even buffer!\r\n\r\nAllegra asked her magic robot who has the steeliest buns. The magic robot answered \"Titanium White.\" which made Allegra angry. She went to capture Titanium White. You followed, but you can\'t keep up with those powerful legs.\r\n\r\nAllegra was busy doing something with \"Titanium White.\" So, she asked her Cobalt Sufferfish to defeat you. You defeated it, right?\r\n\r\nAllegra has captured Titanium White and threatened to remove her as a rival. This sounds like trouble for Titanium White! Go after them, quick!\r\n\r\nYou rescued Titanium White...sort of. Unfortunately, Allegra has stolen her motivation, perseverance, and enthusiasm - the three keys to Titanium White\'s training. There must be a way to get them back!\r\n\r\nYou won the first key from the gym! But it hasn\'t had much of an effect on Titanium White. It looks like you\'ll need all three of them before she\'s back to normal.\r\n\r\nYou won the third key from the gym! Titanium White is back to her old cybernetic self. Allegra was shocked by this revelation but seemed fine with being the best all-natural runner.', 'https://static.wikia.nocookie.net/ringfitadventure/images/4/49/World_16_map_2.png'),
(17, 'The Boy Who Howled Wolf', 'You defeated Allegra, but Dragaux is still out there working on his legs. Head out and stop him!\r\n\r\nYou met Linus, a boy who lies... for some reason. The townspeople hate him, because he always lies. Ring and the Trainee figured out that animals could be controlled by the dark influence!\r\n\r\nLinus followed you quietly, watching to see how you\'d handle the berserk animals. When he saw your power, he pleaded with you to be his coach. It seems there\'s someone in town that he wants to keep safe.\r\n\r\nYou later figured out that Linus was told by Dragaux to lie, so he could make his legs stronger. Dragaux lied, and you want to go after him before it\'s too late!\r\n\r\nYou ran into Honey, who seemed to be the person Linus was worried about. She promised to return to town and tell everyone how helpful Linus was.', 'https://static.wikia.nocookie.net/ringfitadventure/images/6/6f/World_17_map.png'),
(18, 'The Iceman Flexeth', 'It turned out to be Dragaux who tricked Linus into lying. You sent Dragaux packing and the townspeople forgave Linus, making it a happy ending for all.\r\n\r\nThermia\'s friend stranded in the snow turned out to be Honey from the General Store. Thanks to you, both Thermia and Honey made it safely back to town. But why weren\'t they dressed for the weather?\r\n\r\nThermia and Honey explained that their reason being underdressed is because of their new chief\'s orders. From the sound of it, this new chief can only be Armando!\r\n\r\nYou helped a young man by giving him some warm soup. The man was going to the Chief\'s House but warned you of the guard dog that the chief keeps.', 'https://static.wikia.nocookie.net/ringfitadventure/images/3/30/World_18_map.png'),
(19, 'Getting Rusty', 'You defeated Armando, who slip a bit of information about Dragaux\'s plans. He\'s gone to train his arms in the next land!\r\n\r\nYou travelled with Ring to the Robot Kingdom. Since you couldn\'t understand the robot language, Binarese, Honey suggested wearing clothes from the Fitness Machine set, which makes it possible to communicate with robots and understand Binarese.\r\n\r\nThough Honey from the General Store spoke Binarese fluently, you didn\'t understand it at all. Fortunately, there\'s an easy solution: anyone who wears the Fitness Machine clothing set can speak Binarese.\r\n\r\nYou found a robot lying on the ground and unable to move. When you gave the robot a smoothie, it recovered, and had a few unkind things to say about a certain dragon. Is Dragaux up to something sinister here, too?\r\n\r\nYou met a robot having trouble getting past the checkpoint that Dragaux had set up. You cleared out the Though Honey from the General Store spoke Binarese fluently, you didn\'t understand it at all. Fortunately, there\'s an easy solution: anyone who wears the Fitness Machine clothing set can pronounce Binarese.\r\n\r\nBefore the start of Ohwanoh factory, you found a robot lying on the ground and unable to move. When you gave the robot a smoothie, it recovered and had a few unkind things to say about a dragon. Is Dragaux up to something sinister here, too?\r\n\r\nBefore Heave-Ho checkpoint, you met a robot having trouble getting past the checkpoint that Dragaux had set up. You cleared out the checkpoint and received the robot\'s inimitable thanks.\r\n\r\nYou found another robot collapsed on the ground. When you gave the robot the smoothie it wanted, even Ring was surprised by its advanced features.\r\n\r\nYou spoke to a robot who complained Dragaux closed all training gyms that didn\'t specialize in arms. The Battle Gym, on the other hand, was still open for business. You wasted no time in overcoming the nearest Battle Gym.\r\n\r\nYou found a golden robot collapsed on the ground. Ring got excited to see this one\'s features, but when you fed it a smoothie, the spectacle only left him speechless. Maybe you\'d better just head for Dragaux.', 'https://static.wikia.nocookie.net/ringfitadventure/images/9/95/World_19_map.png'),
(20, 'The City of Open Eyes', 'You defeated Dragaux once more, despite all of his training. He seems convinced that what he needs now is to focus on balancing his muscle groups. Which must mean he plans to train with Guru Andma!\r\n\r\nYou discovered it was Guru Andma teaching Dragaux how to balance his training. Now Dragaux is still at large somewhere, making his final preparations!\r\n\r\nWhile tracking down the reason for the loud clanging sounds from Dragaux Stadium, you met Snoozie, who was running feverishly to resist the pull of sleep. Ring tricked her into sleeping, giving her some much-needed rest.\r\n\r\nThough Ring tricked Snoozie into sleeping, she returned the favor by tricking you into giving her smoothies that would keep her awake. The only way to help her now seems to be to find Dragaux and stop his cruel scheme!', 'https://static.wikia.nocookie.net/ringfitadventure/images/7/7a/World_20_map_2.png'),
(21, 'Le pays des Limbes', 'Réalisant que sa seule énergie d\'exercice ne suffisait pas, Dragaux a absorbé les Quatre Maîtres et a fui vers Finalia. Il n\'y a pas de temps à perdre !\r\n\r\nEn poursuivant Dragaux jusqu\'à Finalia, tu t\'es perdu dans Between Land, où le monde des vivants est relié à l\'au-delà. Soudain, un fantôme est apparu devant vous !\r\n\r\nAvec l\'aide du mystérieux fantôme, vous avez surmonté les obstacles. Ring a été ému par votre force lorsque vous vous êtes approché de l\'entrée du Pays d\'Hadès. ', 'https://static.wikia.nocookie.net/ringfitadventure/images/a/af/World_21_map.png'),
(22, 'Land of Hades', 'The mysterious ghost left after whispering \"Four...Masters...\" Are the Four Masters in the Land of Hades? And just where is this \"Finalia\" where Dragaux awaits?\r\n\r\nDragaux\'s training will be complete at any moment, and you\'re the only one left who can stop him! The Four Masters are willing to train you, but there\'s a slight problem: they\'ve been reduced to nothing more than wandering souls.\r\n\r\nYou met with the spirit of Allegra, who assisted you with your leg training. Though Allegra had been consumed with jealousy, she seems to have overcome that.\r\n\r\nYou met with the spirit of Armando, who assisted you with your arm training. It turned out that Armando had begun fitness in order to get a girlfriend.\r\n\r\nYou met with the spirit of Abdonis, who assisted you with your abs training. In return, you taught Abdonis the importance of trusting others.\r\n\r\n[Placeholder bracket as there may be a summary missing.]\r\n\r\nGuru Andma\'s spirit was waiting for you to instruct you in some intense training. She seemed quite energetic, considering that she\'s only now a spirit.\r\n\r\nUpon defeating Guru Andma\'s pet dog, Sir Grrrus, she declared you ready to face your final challenge within the Land of Hades.', 'https://static.wikia.nocookie.net/ringfitadventure/images/f/f7/World_22_map_2.png'),
(23, 'Finalia', 'The Four Masters have conquered their own weaknesses and helped you to conquer yours as well. Vowing to save them at all costs, you headed for Finalia where Dragaux awaits!\r\n\r\nYou have arrived at last at Finalia. If you cannot clear away Dragaux\'s Dark Influence here once and for all, this world will be lost forever.', 'https://static.wikia.nocookie.net/ringfitadventure/images/8/82/World_23_map.png');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `rfa_mondes`
--
ALTER TABLE `rfa_mondes`
  ADD PRIMARY KEY (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
